---
apiVersion: v1
kind: Secret
metadata:
  name: user9-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-rbrc5/user9-gateway-gitops
